task9
Barburon/Project-one pull request #10
Opened 2020-12-25 20:42 UTC by nourish1709

Class UserService.java was added

2020-12-25 22:12 UTC, Julia1910 requested changes

2020-12-25 22:12 UTC, Julia1910 commented on src/main/java/com/cursor/service/UserService.java
> +        if (usersContain(user.getUsername(), user.getPassword()) || user.getUsername().isBlank() || user.getPassword().isBlank()) {
Split this "if" into two lines

2020-12-25 22:12 UTC, Julia1910 commented on src/main/java/com/cursor/service/UserService.java
> +    private void ifExists(int id) { // check if user exists and throws exception if not
Maybe it will be better to make return type boolean

2020-12-25 22:13 UTC, ShvedovIllia requested changes

2020-12-25 22:13 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserService.java
> +    private boolean usersContain(String userName, String password) { // check if the user with inputted username and password exists in userDao
remove comment

2020-12-25 22:13 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserService.java
> +    private void ifExists(int id) { // check if user exists and throws exception if not
rename to "checkExistence"

2020-12-25 22:13 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserService.java
> +            if (user.getUsername().equals(userName) && user.getPassword().equals(password)) {
hmmmm.. it means, that we can't create 2 users with the same password?) I guess, not a good idea=)

2020-12-25 22:13 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserService.java
> +    private boolean usersContain(String userName, String password) { // check if the user with inputted username and password exists in userDao
would be better to override the "checkExistence" method)

2020-12-25 22:13 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserService.java
> +            users.create(user);
would be great to set some requirements for password) at least, a password should contain 8 chars)
and you should check it here

2020-12-25 22:13 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserService.java
> +    private static UserService userService;
let us discuss this point in our chat. I totally don't understand the reason for using a singleton here

2020-12-25 22:13 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserService.java
> +public class UserService implements com.cursor.service.interfaces.UserService {
bad interface name. use the line below instead
public class UserServiceImpl implements UserService {

2020-12-25 22:14 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserService.java
> +    private void ifExists(int id) { // check if user exists and throws exception if not
oh, I've missed the comment =)
remove it, please)

2020-12-26 10:30 UTC, Julia1910 submitted a review, later dismissed

2020-12-26 11:10 UTC, ShvedovIllia requested changes

2020-12-26 11:10 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserServiceImpl.java
> +            if (user.getUsername().equals(userName) && user.getPassword().equals(password)) {
still actual. remove password check) would be enough to check if a user with this username is present)

2020-12-26 11:10 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserServiceImpl.java
> +            throw new BadRequestException("Username or password is incorrect");
move exception throwing to checkExistence method

2020-12-26 11:10 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserServiceImpl.java
> +            throw new NotFoundException("The user was not found");
move exception throwing to checkExistence method

2020-12-26 11:30 UTC, nourish1709 commented on src/main/java/com/cursor/service/UserServiceImpl.java
> +            if (user.getUsername().equals(userName) && user.getPassword().equals(password)) {
I use this method for logging the user in. His username and password must be correct. For checking just username I created overridden method checkExistence(String userName)

2020-12-26 14:37 UTC, Julia1910 requested changes

2020-12-26 14:37 UTC, Julia1910 commented on src/main/java/com/cursor/service/UserServiceImpl.java
Must be a constructor.

2020-12-26 14:37 UTC, Julia1910 commented on src/main/java/com/cursor/service/UserServiceImpl.java
>              if (user.getUsername().equals(userName)) {
Maybe you forget to add "!" there?

2020-12-26 14:37 UTC, Julia1910 commented on src/main/java/com/cursor/service/UserServiceImpl.java
>              if (user.getUsername().equals(userName) && user.getPassword().equals(password)) {
Maybe you forget to add "!" there?

2020-12-26 16:01 UTC, nourish1709 commented on src/main/java/com/cursor/service/UserServiceImpl.java
>              if (user.getUsername().equals(userName)) {
This method is used when creating account - if there is already account with such userName, it throws exception

2020-12-26 16:22 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserServiceImpl.java
> +                throw new NotFoundException("The user was not found");
bad error message. should be "User already exist" or smth like this)

2020-12-26 16:55 UTC, ShvedovIllia approved these changes

2020-12-26 18:31 UTC, nourish1709 commented on src/main/java/com/cursor/service/UserServiceImpl.java
Illia said because it's empty and there's no reason to add it

2020-12-26 18:37 UTC, Julia1910 approved these changes

2020-12-26 18:41 UTC, Barburon approved these changes

2020-12-26 19:03 UTC, merged