Task 10. Singleton class TicketService.java was added
Barburon/Project-one pull request #11
Opened 2020-12-25 21:43 UTC by nourish1709

2020-12-25 22:04 UTC, ShvedovIllia requested changes
and what the reason for using a singleton for this service? why I can't create 2 or more instances of these services if I need them?

2020-12-25 22:04 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/TicketService.java
> +    private void ifExists(int id) { // check if ticket exists and throws exception if not
remove comment.

2020-12-25 22:04 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/TicketService.java
> +    private void ifExists(int id) { // check if ticket exists and throws exception if not
and, i guess, would be better to rename it to "checkExistence". as for me, looks more explicit

2020-12-25 22:07 UTC, Julia1910 commented on src/main/java/com/cursor/service/TicketService.java
> +    private void ifExists(int id) { // check if ticket exists and throws exception if not
or make it boolean

2020-12-25 22:11 UTC, Julia1910 commented on src/main/java/com/cursor/service/TicketService.java
> +    private TicketService() { }
We decided to make classes TicketService and UserService as Singletons because these classes have a connection with saving data to maps. That's why we need only one instance.

2020-12-25 22:33 UTC, Julia1910 requested changes

2020-12-25 22:33 UTC, Julia1910 commented on src/main/java/com/cursor/service/TicketService.java
> +    private void ifExists(int id) { // check if ticket exists and throws exception if not
Make it boolean

2020-12-26 10:33 UTC, Julia1910 approved these changes

2020-12-26 11:07 UTC, ShvedovIllia requested changes

2020-12-26 11:07 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/TicketServiceImpl.java
> +            throw new NotFoundException(USER_NOT_FOUND);
you throw the same error three times. would be better to move exception throwing to checkExistence method)
copy-paste - bad point in programming=)

2020-12-26 14:41 UTC, Julia1910 requested changes

2020-12-26 14:41 UTC, Julia1910 commented on src/main/java/com/cursor/service/TicketServiceImpl.java
> +
There must be a constructor

2020-12-26 16:55 UTC, ShvedovIllia approved these changes

2020-12-26 18:32 UTC, nourish1709 commented on src/main/java/com/cursor/service/TicketServiceImpl.java
> +
Illia said because it's empty and there's no reason to add it

2020-12-26 18:39 UTC, Julia1910 approved these changes

2020-12-26 18:40 UTC, Barburon approved these changes

2020-12-26 19:03 UTC, merged