Task 2+3
Barburon/Project-one pull request #15
Opened 2020-12-28 19:43 UTC by Barburon

create class Actions, Menu, fixed TicketDao

2020-12-28 22:31 UTC, AmorBielyi approved these changes

2020-12-29 10:56 UTC, nourish1709 approved these changes

2020-12-30 11:30 UTC, Julia1910 requested changes

2020-12-30 11:30 UTC, Julia1910 commented on src/main/java/com/cursor/view/Actions.java
> +            switch (menu) {
There must be try/catch

2020-12-30 11:30 UTC, Julia1910 commented on src/main/java/com/cursor/view/LoginPage.java
>                  case 1 -> {
There must be a try/catch

2020-12-31 12:57 UTC, Julia1910 approved these changes

2020-12-31 15:51 UTC, AmorBielyi approved these changes

2020-12-31 16:16 UTC, ShvedovIllia approved these changes

2020-12-31 16:16 UTC, merged