Task 13 done. Bugs were fixed
Barburon/Project-one pull request #16
Opened 2021-01-01 15:30 UTC by nourish1709

2021-01-02 10:49 UTC, Julia1910 approved these changes

2021-01-02 16:45 UTC, Barburon submitted a review, later dismissed

2021-01-03 15:08 UTC, ShvedovIllia requested changes

2021-01-03 15:08 UTC, ShvedovIllia commented on src/main/java/com/cursor/view/Actions.java
> +                User asignee = LoginPage.findUser();
the same as above. Actions should not know about the LoginPage. it is different flows. please, apply it everywhere

2021-01-03 15:08 UTC, ShvedovIllia commented on src/main/java/com/cursor/view/LoginPage.java
> +    public static int getNum() {
this method should be removed from here

2021-01-03 15:08 UTC, ShvedovIllia commented on src/main/java/com/cursor/view/LoginPage.java
> +            int menu1 = getNum();
menu1 - a bad name
try to avoid numbers in namings

2021-01-03 15:08 UTC, ShvedovIllia commented on src/main/java/com/cursor/view/LoginPage.java
> +    public static final String USER_NOT_FOUND = "[...The user with such ID wasn't found. Please enter ID again...]";
this constant should be removed from here. it should be in the file with an error contants

2021-01-05 14:35 UTC, ShvedovIllia requested changes

2021-01-05 14:35 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/TicketServiceImpl.java
> +            throw new NotFoundException();
why have you decided to remove the error message?) I guess it should be here

2021-01-05 14:35 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/exceptions/NotFoundException.java
> +    private static final String USER_NOT_FOUND = "[...The object with such ID wasn't found. Please enter ID again...]";
bad( 
you should create a separate file with constants) and move it there

2021-01-06 13:50 UTC, lazermann111 commented on src/main/java/com/cursor/service/UserServiceImpl.java
> +        } else if (user.getPassword().length() < 8 ||  user.getUsername().length() < 3) {
please use constants for min username/pass lenth instead magic numbers

2021-01-06 13:50 UTC, lazermann111 commented on src/main/java/com/cursor/service/UserServiceImpl.java
> +                || entity.getUsername().isBlank() || entity.getPassword().isBlank()
please use constants for min username/pass lenth instead magic numbers

2021-01-06 13:51 UTC, lazermann111 commented on src/main/java/com/cursor/view/Actions.java
> +    private final TicketServiceImpl ticketService = new TicketServiceImpl();
Declared type must be an interface

2021-01-06 13:54 UTC, lazermann111 commented on src/main/java/com/cursor/view/Utils.java
> +    public static final UserServiceImpl userService = new UserServiceImpl();
In general its not a common practice to inject services in utility classes (classes with only static methods)

2021-01-06 13:55 UTC, lazermann111 commented on src/main/java/com/cursor/view/LoginPage.java
> +        User newUser = Utils.findUser();
"newUser" is misleading, its actually an existing user

2021-01-06 13:56 UTC, lazermann111 commented on src/main/java/com/cursor/view/LoginPage.java
> +                System.out.println("[...Username should NOT be empty. Password must contain at least 8 characters...]");
it says " Username should NOT be empty.", but actually it should contain at least 3 symbols :)

2021-01-06 13:57 UTC, lazermann111 commented on src/main/java/com/cursor/view/LoginPage.java
> +    public static final UserServiceImpl userService = new UserServiceImpl();
Declared type must be an interface

2021-01-06 14:00 UTC, lazermann111 commented on src/main/java/com/cursor/view/Actions.java
> +        boolean wrongInfo = true;
pattern with 
```
boolean wrongInfo = true;
while (wrongInfo) {
```
seems wrong, it means that user will stuck in loop untill details will be not filled, and he cant change any menu option?

2021-01-06 14:00 UTC, lazermann111 commented on src/main/java/com/cursor/view/Actions.java
> +        while (wrongInfo) {
pattern with 
```
boolean wrongInfo = true;
while (wrongInfo) {
```
seems wrong, it means that user will stuck in loop untill details will be not filled, and he cant change any menu option?

2021-01-06 14:01 UTC, lazermann111 commented on src/main/java/com/cursor/view/Actions.java
> +        while (wrongInfo) {
pattern with 
```
boolean wrongInfo = true;
while (wrongInfo) {
```
seems wrong, it means that user will stuck in loop untill details will be not filled, and he cant change any menu option?

2021-01-06 14:01 UTC, lazermann111 commented on src/main/java/com/cursor/view/LoginPage.java
> +        wrongInfo = true;
pattern with 
```
boolean wrongInfo = true;
while (wrongInfo) {
```
seems wrong, it means that user will stuck in loop untill details will be not filled, and he cant change any menu option?

2021-01-06 14:01 UTC, lazermann111 commented on src/main/java/com/cursor/view/LoginPage.java
> +        while (wrongInfo) {
pattern with 
```
boolean wrongInfo = true;
while (wrongInfo) {
```
seems wrong, it means that user will stuck in loop untill details will be not filled, and he cant change any menu option?

2021-01-06 14:01 UTC, lazermann111 requested changes
plz check comments

2021-01-06 17:19 UTC, ShvedovIllia submitted a review, later dismissed

2021-01-06 17:19 UTC, ShvedovIllia commented on src/main/java/com/cursor/view/Actions.java
> +    private static final String TYPE_TO_EXIT = "(for choosing another action enter \"exit\")";
this constant should be moved to the file with constants because you use it at least in 2 files)
moreover, if we need to change this string, we will change it twice instead of one file)

2021-01-06 17:19 UTC, ShvedovIllia commented on src/main/java/com/cursor/view/LoginPage.java
> +                System.out.println("[...Username must contain at least 3 symbols. Password must contain at least 8 symbols...]");
would be better to use params here) the same, as in the previous comment. if we will change the constants in the appropriate file, we will need to change this sout as well. so, use constants for username length and password length

2021-01-06 17:19 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/UserServiceImpl.java
> +    private static final int PASSWORD_MIN_LENGTH = 8;
I think that would be better to have these constants in the appropriate file)

2021-01-07 08:32 UTC, lazermann111 approved these changes

2021-01-07 08:40 UTC, Barburon submitted a review, later dismissed

2021-01-07 09:35 UTC, lazermann111 approved these changes

2021-01-07 09:37 UTC, Barburon approved these changes

2021-01-07 09:40 UTC, Julia1910 approved these changes

2021-01-07 09:41 UTC, merged