Task 15. Create Dashboard
Barburon/Project-one pull request #17
Opened 2021-01-02 13:47 UTC by Julia1910

2021-01-02 16:45 UTC, Barburon approved these changes

2021-01-03 15:11 UTC, ShvedovIllia requested changes

2021-01-03 15:11 UTC, ShvedovIllia commented on src/main/java/com/cursor/view/Actions.java
> +
remove empty line

2021-01-03 15:11 UTC, ShvedovIllia commented on src/main/java/com/cursor/view/Actions.java
> +
remove empty line

2021-01-03 15:11 UTC, ShvedovIllia commented on src/main/java/com/cursor/service/DashboardImpl.java
> +
remove empty lines here and below

2021-01-04 18:57 UTC, AmorBielyi approved these changes

2021-01-05 14:37 UTC, ShvedovIllia approved these changes

2021-01-06 14:03 UTC, lazermann111 commented on src/main/java/com/cursor/service/DashboardImpl.java
> +            if (ticket.getAssignee().equals(user)) {
Its a common situation in real Jira when ticket doesnt have an assignee (unassigned ticket), so maybe it makes sesnse to add null check here

2021-01-06 14:03 UTC, lazermann111 commented on src/main/java/com/cursor/service/DashboardImpl.java
> +        for (Ticket ticket : tickets.getAll()) {
Its a common situation in real Jira when ticket doesnt have an assignee (unassigned ticket), so maybe it makes sesnse to add null check here

2021-01-06 14:04 UTC, lazermann111 approved these changes
Approved with minor comment

2021-01-06 14:06 UTC, merged