Task 11. Create exceptions
Barburon/Project-one pull request #2
Opened 2020-12-20 14:49 UTC by Julia1910

Added two exceptions with a base class and enum of error code.

2020-12-20 15:29 UTC, lazermann111 requested changes

2020-12-20 15:29 UTC, lazermann111 commented on src/main/java/com/cursor/service/exceptions/BaseException.java
> +    private ErrorCode errorCode;
Consider to extend from RuntimeException in order to not add throws to all methods

2020-12-21 16:49 UTC, Barburon approved these changes

2020-12-21 17:01 UTC, lazermann111 approved these changes

2020-12-21 17:10 UTC, AmorBielyi approved these changes

2020-12-21 17:17 UTC, Julia1910 commented on src/main/java/com/cursor/service/exceptions/BaseException.java
> +    private ErrorCode errorCode;
Resolved

2020-12-21 17:18 UTC, Barburon approved these changes

2020-12-21 17:18 UTC, Barburon approved these changes

2020-12-21 17:19 UTC, Barburon approved these changes

2020-12-21 17:19 UTC, Barburon approved these changes

2020-12-21 17:19 UTC, Barburon approved these changes

2020-12-21 17:19 UTC, Barburon approved these changes

2020-12-21 17:19 UTC, Barburon approved these changes

2020-12-21 17:19 UTC, Barburon approved these changes

2020-12-21 17:21 UTC, merged