Created interface Menu
Barburon/Project-one pull request #5
Opened 2020-12-22 21:38 UTC by Barburon

Task1 done, created interface Menu

2020-12-22 21:43 UTC, AmorBielyi submitted a review, later dismissed

2020-12-22 21:45 UTC, illia-nerdysoft requested changes

2020-12-22 21:45 UTC, illia-nerdysoft commented on src/main/java/com/cursor/view/interfaces/Menu.java
> +
remove empty lines 11 and 12

2020-12-22 22:26 UTC, Julia1910 approved these changes

2020-12-23 13:58 UTC, Barburon reviewed
done

2020-12-23 22:10 UTC, ShvedovIllia requested changes

2020-12-23 22:10 UTC, ShvedovIllia commented on src/main/java/com/cursor/view/interfaces/Menu.java
> +
looks, it is still actual)
the empty line still present)

2020-12-25 13:54 UTC, ShvedovIllia approved these changes

2020-12-25 14:07 UTC, Julia1910 approved these changes

2020-12-25 15:22 UTC, AmorBielyi approved these changes

2020-12-25 15:27 UTC, merged