Task 4.  Create a User, Ticket class and a UserDao, TicketDao class that implement CRUD
Barburon/Project-one pull request #7
Opened 2020-12-23 21:48 UTC by AmorBielyi

2020-12-23 22:08 UTC, ShvedovIllia requested changes

2020-12-23 22:08 UTC, ShvedovIllia commented on src/main/java/com/cursor/dao/impls/UserDao.java
> +
remove empty line

2020-12-23 22:08 UTC, ShvedovIllia commented on src/main/java/com/cursor/model/Ticket.java
> +    String name;
all fields should be private

2020-12-23 22:08 UTC, ShvedovIllia commented on src/main/java/com/cursor/model/User.java
> +    String password;
all fields should be private

2020-12-24 19:27 UTC, Julia1910 approved these changes

2020-12-24 20:16 UTC, Barburon approved these changes

2020-12-24 21:49 UTC, nourish1709 approved these changes

2020-12-25 13:56 UTC, ShvedovIllia approved these changes

2020-12-25 13:56 UTC, merged